### PR TITLE
DLS-9979 - improve session/request id logging

### PR DESCRIPTION
**Pull request by TomRafferty**
['[CGC Calcs] Improve Session/request ID Logging' (DLS-9979)](https://jira.tools.tax.service.gov.uk/browse/DLS-9979)

### CODE REVIEW

**Comment by johno1985** [comment]
I have one unit test failure locally config.CgtErrorHandlerSpec

**Comment by johno1985** [comment]
There are also some unused and deprecated warnings

**Comment by TomRafferty** [comment]
> I have one unit test failure locally config.CgtErrorHandlerSpec

nothing failing on my end or jenkins 🤔

**Comment by TomRafferty** [comment]
> There are also some unused and deprecated warnings

I can see 4 warnings to do with an implicit value that is "unused" however removing causes issues

**Comment by johno1985** [comment]
> > There are also some unused and deprecated warnings
> 
> I can see 4 warnings to do with an implicit value that is "unused" however removing causes issues

try replacing with _

**Comment by johno1985** [comment]
> > I have one unit test failure locally config.CgtErrorHandlerSpec
> 
> nothing failing on my end or jenkins 🤔

can you change the default timeout to 10 seconds on line 36 of CommonPlaySpec?

**Comment by TomRafferty** [comment]
> > > I have one unit test failure locally config.CgtErrorHandlerSpec
> > 
> > 
> > nothing failing on my end or jenkins 🤔
> 
> can you change the default timeout to 10 seconds on line 36 of CommonPlaySpec?

done 👍

**Review by johno1985 — APPROVED** [review]

**Pull request merged**
